name: smart_scroll_view
description: the most advanced scroll view
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.0.1
  pull_to_refresh: ^2.0.0
  figma_to_flutter: ^0.0.1
  custom_refresh_indicator: ^2.2.1
  easy_refresh: ^3.3.2+1
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0

flutter:
